import time
import pyautogui
pyautogui.alert("Código sendo executado, aguarde")
pyautogui.hotkey('winleft','m')
time.sleep(1)
pyautogui.press('printscreen')
pyautogui.press('winleft')
time.sleep(1)
pyautogui.write('mspaint')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.hotkey('ctrl','v')
time.sleep(1)
pyautogui.hotkey('alt','f')
time.sleep(1)
pyautogui.hotkey('alt','s')
time.sleep(1)
pyautogui.press('enter')
pyautogui.write('Nome do arquivo TESTE')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey('win','m')
time.sleep(2)
pyautogui.press('winleft')
time.sleep(2)
pyautogui.write('mspaint')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey('alt','f')
time.sleep(2)
pyautogui.hotkey('alt','a')
time.sleep(2)
pyautogui.write('Nome do arquivo TESTE.png')
time.sleep(3)
pyautogui.press('enter')
time.sleep(1)
pyautogui.alert("Código executado com sucesso! Obrigado : ) ")